apiVersion: v1
kind: Service
metadata:
  name: pv-demo-service
  namespace: pv-manager
  labels:
    app: pv-demo-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500     # Exposes UI on standard port
      protocol: TCP
  selector:
    app: pv-demo-app
